<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:include schemaLocation="common.xsd"/>
  <xs:element name="RK7Query">
    <xs:annotation>
      <xs:documentation xml:lang="ru">[Кассовый сервер]: Проверка коректности пароля 
Для работы запроса требуется лицензия на xml. 
После ошибки проверки пароля, следующий запрос проверки пароля будет обработан только через секунду (защита от brutforce).
</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:all>
        <xs:element name="RK7CMD">
          <xs:complexType>
           <xs:sequence>   
              <xs:element name="Employee" type="refItem" minOccurs="1" maxOccurs="1">
                <xs:annotation>
                  <xs:documentation xml:lang="ru">Работник</xs:documentation>
                </xs:annotation>
              </xs:element>
           </xs:sequence>   
            <xs:attribute name="password" type="xs:normalizedString" use="required">
              <xs:annotation>
                <xs:documentation xml:lang="ru">Пароль (в зашифрованном виде).
Алгоритм шифрования пароля:
Пароль шифруется XOR шифрованием с ключом, результат переводится в base64. 
Ключ рассчитывается по формуле: идентификатор работника (EmpID) переводится в десятичный формат, полученная строка преобразуется в base64.

Key = base64 (EmpID.toString)
tmp = Password.xorString(Key)
CryptedPassword = base64(tmp)
</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="CMD" fixed="CheckPassword"/>
          </xs:complexType>
        </xs:element>
      </xs:all>
    </xs:complexType>
  </xs:element>
</xs:schema>
