<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:include schemaLocation=".\common.xsd"/>
  <xs:complexType name="poFiscalDocInfo">
    <xs:sequence>
      <xs:element name="FiscDev" type="refItem" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation xml:lang="ru">Тип фискального устройства. 
Указанное значение заносится в поле PrintChecks.FiscDev</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="PrintNumber" type="xs:nonNegativeInteger" use="required">
      <xs:annotation>
        <xs:documentation xml:lang="ru">Печатный номер чека, в России номер чека ФН. 
Указанное значение заносится в поле PrintChecks.PrintNumber.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="FiscDocNumber" type="xs:nonNegativeInteger" use="required">
      <xs:annotation>
        <xs:documentation xml:lang="ru">Фискальный номер документа, в России номер документа ФН. 
Указанное значение заносится в поле PrintChecks.FiscDocNumber.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="GlobalFiscalId" type="xs:normalizedString" use="optional">
      <xs:annotation>
        <xs:documentation xml:lang="ru">Глобальный номер чека, в России не используется.
Указанное значение заносится в поле PrintChecks.GlobalFiscalID.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="ExtFiscID" type="xs:normalizedString" use="required">
      <xs:annotation>
        <xs:documentation xml:lang="ru">Номер фискального регистратора. 
Указанное значение заносится в поле PrintChecks.ExtFiscID.  
          </xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="FiscShiftNum" type="xs:positiveInteger" use="optional">
      <xs:annotation>
        <xs:documentation xml:lang="ru">Номер фискальной смены фискального регистратора. 
Указанное значение заносится в поле PrintChecks.iFiscShift.  
          </xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:element name="RK7Query">
    <xs:annotation>
        <xs:documentation xml:lang="ru">[Кассовый сервер] Удалить заказ</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:all>
    <xs:element name="RK7CMD">
      <xs:complexType>
        <xs:all>
          <xs:element name="Order" type="orderElement" minOccurs="1">
            <xs:annotation>
              <xs:documentation xml:lang="ru">Заказ</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="Station" type="refItem" minOccurs="1">
            <xs:annotation>
              <xs:documentation xml:lang="ru">Станция</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="Manager" type="refItem" minOccurs="1">
            <xs:annotation>
              <xs:documentation xml:lang="ru">Менеджер, удаляющий заказ</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="DeleteReason" type="refItem" minOccurs="1">
            <xs:annotation>
              <xs:documentation xml:lang="ru">Причина удаления</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="FiscalDocInfo" type="poFiscalDocInfo" minOccurs="0">
            <xs:annotation>
              <xs:documentation xml:lang="ru">Информация о фискальном документе. Для использования в отчетах.</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:all>
        <xs:attribute name="CMD" ype="xs:string" use="required" fixed="VoidOrder"/>
        <xs:attribute name="lockguid" type="xs:normalizedString" default="">
          <xs:annotation>
            <xs:documentation xml:lang="ru">Токен блокировки (идентификатор сессии блокировки). С версии 7.6.4.006.
              При блокировке заказа использовать указанный токен. Если заказ был заблокирован, 
              то проверить токен блокировки, выдавать ошибку если заказ был заблокирован при помощи другого токена
            </xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute name="sendtovdu" type="xs:boolean" default="true">
          <xs:annotation>
            <xs:documentation xml:lang="ru">Флаг "Отправить заказ на VDU". Если включен, то заказ будет передан на VDU, иначе не будет. Версия 7.6.4.032+</xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute name="change_guids" type="xs:boolean" default="true">
          <xs:annotation>
            <xs:documentation xml:lang="ru">Флаг "Изменить GUID элементов". Если включен, то у заказа и у всех элементов его состава будет изменен guid. Версия 7.6.5.189+</xs:documentation>
          </xs:annotation>
        </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:all>
    </xs:complexType>
  </xs:element>
</xs:schema>
