<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:include schemaLocation="common.xsd"/>
  <xs:element name="RK7Query">
    <xs:annotation>
      <xs:documentation xml:lang="ru">Проверка возраста через MAX</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="RK7CMD">
          <xs:complexType>
            <xs:attribute name="CMD" fixed="VerifyAgeViaMax"/>
            <xs:attribute name="sessionID" type="xs:token" use="required">
              <xs:annotation>
                <xs:documentation xml:lang="ru">id сессии из QR-кода в мессенджере MAX</xs:documentation>
              </xs:annotation>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
