<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:include schemaLocation="common.xsd"/>
  <xs:element name="RK7QueryResult" type="RK7QueryResult">
    <xs:annotation>
      <xs:documentation xml:lang="ru">xml-ответ AddBatchOfGoods</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="RK7QueryResult">
          <xs:all>
            <xs:element name="Batch" minOccurs="1" maxOccurs="1">
              <xs:attribute name="name" type="xs:normalizedString" use="required">
                <xs:annotation>
                  <xs:documentation xml:lang="ru">Наименование продукта</xs:documentation>
                </xs:annotation>
              </xs:attribute>
              <xs:attribute name="quantity" type="xs:nonNegativeInteger" use="required">
                <xs:annotation>
                  <xs:documentation xml:lang="ru">Остаток блюда (в тысячных долях)</xs:documentation>
                </xs:annotation>
              </xs:attribute>
              <xs:attribute name="markingData" type="xs:base64binary" use="required">
                <xs:annotation>
                  <xs:documentation xml:lang="ru">Строка с данными в base64 формате</xs:documentation>
                </xs:annotation>
              </xs:attribute>
              <xs:attribute name="gtin" type="gtinString" use="required">
                <xs:annotation>
                  <xs:documentation xml:lang="ru">ГТИН из марки</xs:documentation>
                </xs:annotation>
              </xs:attribute>
              <xs:attribute name="startDateTime" type="xs:dateTime" use="required">
                <xs:annotation>
                  <xs:documentation xml:lang="ru">Дата и время добавления партии</xs:documentation>
                </xs:annotation>
              </xs:attribute>
              <xs:element name="Author" type="refItem">
                <xs:annotation>
                  <xs:documentation xml:lang="ru">Сотрудник, выполнивший регистрацию партии</xs:documentation>
                </xs:annotation>
              </xs:element>
            </xs:element>
          </xs:all>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
</xs:schema>