<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:include schemaLocation="common.xsd"/>

  <xs:element name="RK7QueryResult">
    <xs:annotation>
      <xs:documentation xml:lang="ru">xml-ответ LowAlcKegStatus</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="RK7QueryResult">
          <xs:sequence>
            <xs:element name="Keg">
              <xs:annotation>
                <xs:documentation xml:lang="ru">Данные по кегу</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="markingData" type="xs:base64Binary" use="required">
                  <xs:annotation>
                    <xs:documentation xml:lang="ru">Марка кега в base64</xs:documentation>
                  </xs:annotation>
                </xs:attribute>
                <xs:attribute name="status" type="HonestSignSendStatus" use="required">
                  <xs:annotation>
                    <xs:documentation xml:lang="ru">Статус кега</xs:documentation>
                  </xs:annotation>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
</xs:schema>
