<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:include schemaLocation="common.xsd"/>
  <xs:element name="RK7QueryResult" type="RK7QueryResult">
    <xs:annotation>
      <xs:documentation xml:lang="ru">xml-ответ ParseMarkingData</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="RK7QueryResult">
          <xs:all>
            <xs:element name="Data" minOccurs="1" maxOccurs="1">
              <xs:attribute name="gtin" type="gtinString" use="required">
                <xs:annotation>
                  <xs:documentation xml:lang="ru">ГТИН из марки</xs:documentation>
                </xs:annotation>
              </xs:attribute>
            </xs:element>
          </xs:all>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
</xs:schema>